import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/ui/Layout";

export const metadata: Metadata = {
  title: "Spider Tech",
  description: "Generated by Usman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
